job = /home/egrasmick/glidein_tester/hello_world.sh
universe = vanilla
executable = $(job)
arguments = 10
log = log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = out.Vanderbilt
error = err.Vanderbilt
request_cpus = 1
request_disk = 100000
request_memory = 10
+WantGlidein3 = true
+osg_site_whitelist="Vanderbilt"
requirements = Glidein_SITE =?= "Vanderbilt"
+WantRHEL6 = true
queue